services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JobRouter\AddOn\Typo3Base\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Dto,Enumeration,Exception,Extension.php}'

  JobRouter\AddOn\Typo3Base\Domain\VariableResolvers\JobRouterLanguageVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/jobrouter-language-variable-resolver'

  JobRouter\AddOn\Typo3Base\Domain\VariableResolvers\LanguageVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/language-variable-resolver'

  JobRouter\AddOn\Typo3Base\Domain\VariableResolvers\LocalisedLabelVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/localised-label-variable-resolver'

  JobRouter\AddOn\Typo3Base\Domain\VariableResolvers\CorrelationIdVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/correlation-id-variable-resolver'

  JobRouter\AddOn\Typo3Base\Domain\VariableResolvers\PageVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/page-variable-resolver'
